---
language: python
python: "2.7"

env:
  - PLAYBOOK=playbook.yml

before_install:
  - uname -a
  - cat /proc/version
  - sudo apt-get update -qq
  - ln -s ansible-role-newrelic ../mauricios.NewRelic

install:
  # Install Ansible.
  - sudo pip install ansible

before_script:
  - "ansible --version"
  - "cd tests"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook $PLAYBOOK --extra --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook $PLAYBOOK --connection=local"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook $PLAYBOOK --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
