---
- debug: var=newrelic verbosity=1
  tags: vars

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- command: php --version
  register: php_present
  ignore_errors: True
  changed_when: False

- include_tasks: setup-PHP-Debian.yml
  when: ansible_os_family == 'Debian' and php_present

- include_tasks: setup-PHP-RedHat.yml
  when: ansible_os_family == 'RedHat' and php_present
