---
- debug: var=newrelic verbosity=1
  tags: vars

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: post-setup.yml
  when: newrelic.license_key
