---
- command: php --version
  register: php_present
  ignore_errors: True
  changed_when: False

- name: Add New Relic license key
  become: yes
  shell: "nrsysmond-config --set license_key={{ newrelic.license_key }}"
  notify: restart newrelic

- include: setup-PHP-Debian.yml
  when: ansible_os_family == 'Debian' and php_present|success

- include: setup-PHP-RedHat.yml
  when: ansible_os_family == 'RedHat' and php_present|success
