---
- name: Install New Relic for PHP with apt
  sudo: yes
  apt:
    name: newrelic-php5
    state: present
    force: yes
  when: php_present|success

- name: Removing New Relic redundant config in PHP conf
  sudo: yes
  file:
    path: /etc/php5/apache2/conf.d/newrelic.ini
    state: absent

- name: Enabling NewRelic module config in PHP conf
  sudo: yes
  command: php5enmod newrelic
  notify: reload apache
  changed_when: False
  when: apache['service'] is defined

- include: setup-PHP.yml
