---
- name: Add the New Relic package repo to apt
  become: yes
  apt_repository:
      repo: "deb http://apt.newrelic.com/debian/ newrelic non-free"
      state: present

- name: Add an Apt signing key for New relic repo
  become: yes
  apt_key:
      id: 548C16BF
      url: https://download.newrelic.com/548C16BF.gpg
      state: present
